version: '2'
services:
  db:
    image: postgres
    volumes:
      - postgres_axelrod:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    command: python run_server.py
    volumes:
      - .:/project
    ports:
      - "8001:8001"
    depends_on:
      - db
    env_file:
      - .env
volumes:
  postgres_axelrod:
